services:
  - type: web
    name: ai-voice-detection
    runtime: python
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python api/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9